### ISSUE TITLE
Oxidized Source http: did not find expected key while parsing a block mapping

### ISSUE THREAD

**Issue by ruslyk123** [ytti/oxidized#1136]
Hello!
Already a week I can not tune Oxidized + LibreNMS...
When you try to set up a sourse, it gives an error:

> гру 26 16:02:59 librenms systemd[1]: Started Oxidized - Network Device Configuration Backup Tool.
> гру 26 16:02:59 librenms systemd[1]: Starting Oxidized - Network Device Configuration Backup Tool...
> гру 26 16:02:59 librenms oxidized[7700]: Error loading config: (<unknown>): did not find expected key while parsing a block mapping at line 58 column 5
> гру 26 16:02:59 librenms oxidized[7700]: /usr/local/share/gems/gems/oxidized-0.21.0/lib/oxidized/config.rb:52:in `rescue in load': Error loading config: (<unknown>): did not find expected key while parsing a block mapping at line 58 column 5 (Oxidized::InvalidConfig)
> гру 26 16:02:59 librenms oxidized[7700]: from /usr/local/share/gems/gems/oxidized-0.21.0/lib/oxidized/config.rb:49:in `load'
> гру 26 16:02:59 librenms oxidized[7700]: from /usr/local/share/gems/gems/oxidized-0.21.0/lib/oxidized/cli.rb:24:in `initialize'
> гру 26 16:02:59 librenms oxidized[7700]: from /usr/local/share/gems/gems/oxidized-0.21.0/bin/oxidized:9:in `new'
> гру 26 16:02:59 librenms oxidized[7700]: from /usr/local/share/gems/gems/oxidized-0.21.0/bin/oxidized:9:in `<top (required)>'
> гру 26 16:02:59 librenms oxidized[7700]: from /usr/local/bin/oxidized:23:in `load'
> гру 26 16:02:59 librenms oxidized[7700]: from /usr/local/bin/oxidized:23:in `<main>'
> гру 26 16:02:59 librenms systemd[1]: oxidized.service: main process exited, code=exited, status=1/FAILURE
> гру 26 16:02:59 librenms systemd[1]: Unit oxidized.service entered failed state.
> гру 26 16:02:59 librenms systemd[1]: oxidized.service failed.

```
[root@librenms oxidized]# gem list | grep -P 'oxidized|slack'
oxidized (0.21.0)
oxidized-script (0.5.0)
oxidized-web (0.9.3)
```
My config:
```
---
username: username
password: password
model: junos
interval: 3600
use_syslog: false
log: /root/.config/oxidized/logs/
debug: false
threads: 30
timeout: 120
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 127.0.0.1:8888
next_adds_job: false
vars:
  ssh_port: 22
  enable: enablepass
  comware_cmdline: ebablepass
groups:
  Hp1910:
    username: someuser
    password: pass
    comware_cmdline: enablepass
models: {}
pid: /root/.config/oxidized/pid
input:
  default: ssh, telnet
  debug: false
  ssh:
    secure: false
#output:
#  default: git
#  file:
#    directory: /root/.config/oxidized/configs
output:
  default: git
  git:
    user: Oxidized
    email: o@example.com
    repo: "/var/lib/oxidized/devices.git"
source:
  default: http
#  csv:
#    file: /root/.config/oxidized/router.db
#    delimiter: !ruby/regexp /:/
#    map:
#      name: 0
#      model: 1
#      username: 2
#      password: 3
#    vars_map:
#      enable: 4
#    gpg: false
#model_map:
#  cisco: ios
#  juniper: junos
  http:
    url: http://127.0.0.1/api/v0/oxidized
    map:
      name: hostname
      model: os
      group: group
     headers:
      X-Auth-Token: 'librenms api randomstring'
model_map:
  hpe: comware
  hp: procurve
  edgeswitch: edgeswitch
gpg: false

```

**Comment by ruslyk123** [comment]
Hello!
I corrected the config to the next state ...
```
[root@librenms oxidized]# cat config
username:
password:
model: cisco
interval: 3600
use_syslog: false
debug: false
threads: 30
timeout: 30
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 127.0.0.1:8888
vars: {}
groups: {}
pid: /root/.config/oxidized/pid
input:
  default: ssh, telnet
  debug: true
  ssh:raised ArgumentError with msg "don't know how to write mypass",
    secure: false
output:
  default: git
  git:
    user: root
    email: email
    repo: "/root/.config/oxidized/configs/devices.git"
source:
    default: http
    debug: true
    http:
      url: http://127.0.0.1/api/v0/oxidized
      map:
        name: hostname
        model: os
        group: group
      vars_map:
        enable: enable
        comware_cmdline: comware_cmdline
      headers:
        X-Auth-Token: 'mytoken' 
models:
  procurve:
    username: mylogin
    password: pass
    vars:
      enable: enablepasss
  edgeswitch:
    username: mylogin
    password: pass
    vars:
      enable: enablepasss
  comware:
    username: mylogin
    password: mypass
    vars:
      comware_cmdline: 512900
#model_map:
#  Procurve: procurve
#  Comware: comware
#  EdgeSwitch: edgeswitch
#  3com: comware
hooks:
  post-commit:
      type: exec
      events: [node_success, post_store]
      cmd: 'cd /root/.config/oxidized/devices.git && git push -f -q /root/.config/oxidized/devices.git master'
rest: localhost:8000/oxidized
```
The previous error has been fixed but got a new one ....
```
гру 27 16:02:48 librenms oxidized[9463]: E, [2017-12-27T16:02:48.234994 #9463] ERROR -- : 172.17.x.x raised ArgumentError with msg "don't know how to write mypass", /root/.config/oxidized/crash.172.17.x.x saved
гру 27 16:02:48 librenms oxidized[9463]: E, [2017-12-27T16:02:48.473823 #9463] ERROR -- : 172.17.x.x raised TypeError with msg "String can't be coerced into Fixnum", /root/.config/oxidized/crash.172.17.x.x saved
гру 27 16:02:48 librenms oxidized[9463]: W, [2017-12-27T16:02:48.802062 #9463]  WARN -- : 172.17.x.x status no_connection, retries exhausted, giving up
гру 27 16:02:53 librenms oxidized[9463]: WARN: tilt autoloading 'tilt/sass' in a non thread-safe way; explicit require 'tilt/sass' suggested.
гру 27 16:03:19 librenms oxidized[9463]: W, [2017-12-27T16:03:19.037378 #9463]  WARN -- : 172.17.x.x raised Timeout::Error with msg "timed out while waiting for more data"
гру 27 16:03:19 librenms oxidized[9463]: W, [2017-12-27T16:03:19.812875 #9463]  WARN -- : 172.17.x.x status no_connection, retry attempt 1
гру 27 16:03:49 librenms oxidized[9463]: W, [2017-12-27T16:03:49.953960 #9463]  WARN -- : 172.17.x.x raised Timeout::Error with msg "timed out while waiting for more data"
гру 27 16:03:50 librenms oxidized[9463]: W, [2017-12-27T16:03:50.823914 #9463]  WARN -- : 172.17.x.x status no_connection, retry attempt 2
гру 27 16:04:20 librenms oxidized[9463]: W, [2017-12-27T16:04:20.962502 #9463]  WARN -- : 172.17.x.x raised Timeout::Error with msg "timed out while waiting for more data"
гру 27 16:04:21 librenms oxidized[9463]: W, [2017-12-27T16:04:21.834490 #9463]  WARN -- : 172.17.x.x status no_connection, retry attempt 3
```
# p.s.
**raised ArgumentError with msg "don't know how to write mypass",** 
**172.17.x.x status no_connection, retries exhausted, giving up**

> {:name=>"172.17.x.x",
>  :full_name=>"172.17.x.x",
>  :ip=>"172.17.x.x",
>  :group=>nil,
>  :model=>"Comware",
>  :last=>
>   {:start=>2017-12-27 14:11:34 UTC,
>    :end=>2017-12-27 14:11:34 UTC,
>    :status=>:no_connection,
>    :time=>0.801221342},
>  :vars=>{:enable=>nil, :comware_cmdline=>nil}}

Who are the ideas?

**Comment by laf** [comment]
Not really sure why this is in your config but you still have a config issue @ruslyk123:

```
ssh:raised ArgumentError with msg "don't know how to write mypass",
```

**Comment by laf** [comment]
No further feedback provided and looks to be config related so closing this, please feel free to reply if you still have issues and we can re-open this.
